##
## config file for DL configuration files-.
##
## @AUTHOR: Fernando Diego Carazo (@buenaluna)-.
##
## start_date: Tue Mar  5 10:18:47 CET 2024-.
## last_modify (Ar): Tue Mar  26 10:18:47 CET 2024-.-.
##

gen_options:
  save: True
  dir_save: '/home/fdcarazo/my_github/TG_ML/dl_model/res_temp/'
  dir_results: '/home/fdcarazo/my_github/TG_ML/dl_model/res_temp/'
  dir_logs: '/home/fdcarazo/my_github/TG_ML/dl_model/res_temp/'
  sheet_name: ''
  vars_names: ["C", "H", "O", "heat_rate", "T", "mass_porc"]
  feat_names: ["C", "H", "O", "heat_rate", "T"]
  targ_names: ["mass_porc"]

dataset:
  path: '/home/fdcarazo/my_github/TG_ML/dl_model/ds/'
  name: 'all.csv'